Feature/add kafka operator support
stackabletech/test-dev-cluster pull request #22
Opened 2021-06-03 13:03 UTC by razvan

## The problem

The Kafka-Operator requires Zookeeper.

## Proposed solution

Install Zookeeper in sidecar containers. Maybe use the Zookeeper operator for the installation.

## How to test

Since there is no `kafka-operator-integration-tests` repository at this moment you need to create an empty folder for now:
```
mkdir kafka-operator-integration-tests
```

Start a test cluster:
```
./init.sh debian kafka-operator
```
Check that a single node Zookpeer cluster has been installed: 
```
docker exec -it debian_sidecar_1 kubectl get zookeeperclusters
```
Run the Kafka operator
```
./run.sh run-operator
```

closes #21

2021-06-04 15:18 UTC, maltesander requested changes
Just some typos, and questions. Looks good otherwise!

2021-06-04 15:18 UTC, maltesander commented on README.md
> +This assumes that you have `xxx-operator` and `xxx-oprerator-integration-tests` repositories checkout on your developmnent system. If any of those repositories are missing, this will not work. There
Some typos here:
This assumes that you have `xxx-operator` and `xxx-operator-integration-tests` repositories checked out on your development system. If any of those repositories are missing, this will not work. There are no sanity checks at the moment.

2021-06-04 15:18 UTC, maltesander commented on README.md
> +When testing the Kafka operator by using `./init.sh debian kafka-operator` for example, an additional sidecar container is started. In this container, the nightly Zookeeper operator and a single node
ZooKeeper. We always write the original form in text, only for the rust variables we switch to "Zookeeper"

2021-06-04 15:18 UTC, maltesander commented on stackable-scripts/cr/zookeeper-cluster.yaml
> +
I know you need to adapt the hostname here but is there any chance to not have a copy of the custom resource in this repo? Ignore this if not possible or too much work. 
Furthermore (or just to keep in mind), we will need the same setup for NiFi (with the sidecar zookeeper) and there we need version 3.5.8.

2021-06-04 15:18 UTC, maltesander commented on stackable-scripts/spec/zookeeper-cluster.yaml
> +        status: {}
Same as with the custom resource. Here you do not need to adapt anything. Can we like link / relate to the one in the zookeeper repo? This will avoid manual updating if changes happen.

2021-06-05 16:34 UTC, razvan commented on README.md
> +This assumes that you have `xxx-operator` and `xxx-oprerator-integration-tests` repositories checkout on your developmnent system. If any of those repositories are missing, this will not work. There
Thanks, they are fixed now.

2021-06-05 16:34 UTC, razvan commented on README.md
> +When testing the Kafka operator by using `./init.sh debian kafka-operator` for example, an additional sidecar container is started. In this container, the nightly Zookeeper operator and a single node
Thanks, they are fixed now.

2021-06-05 16:37 UTC, razvan commented on stackable-scripts/cr/zookeeper-cluster.yaml
> +
Regarding the first question: in a future PR I will remove the CRDs from this repo and `curl` them from GitHub.
Regarding NiFi and different ZooKeeper versions for different operators: that will be another PR :)

2021-06-05 16:38 UTC, razvan commented on stackable-scripts/spec/zookeeper-cluster.yaml
> +        status: {}
Same as above.

2021-06-06 14:42 UTC, maltesander approved these changes
Still see a typo (not sure if its a github problem)

2021-06-06 14:42 UTC, maltesander commented on README.md
> +This assumes that you have `xxx-operator` and `xxx-oprerator-integration-tests` repositories checkout on your developmnent system. If any of those repositories are missing, this will not work. There
Not sure if its still there or problem with github: I still see "developmnent" and Zookeeper instead of ZooKeeper.

2021-06-07 06:16 UTC, merged