Add support for the OPA operator
stackabletech/test-dev-cluster pull request #28
Opened 2021-07-28 14:40 UTC by razvan

Related to [OPA: Enable monitoring](https://github.com/stackabletech/opa-operator/issues/44) so that the OPA operator can be tested here.

2021-07-28 16:38 UTC, maltesander requested changes
One small typo. Looks good otherwise.

2021-07-28 16:38 UTC, maltesander commented on README.md
> +This assumes that you have `xxx-operator` and `xxx-oprerator-integration-tests` repositories checked out on your developmnent system. If the `xxx-operator` is missing the `init.sh` will abort before
Typo in "epmty"

2021-07-29 07:02 UTC, razvan commented on README.md
> +This assumes that you have `xxx-operator` and `xxx-oprerator-integration-tests` repositories checked out on your developmnent system. If the `xxx-operator` is missing the `init.sh` will abort before
Thanks.

2021-07-29 07:30 UTC, maltesander approved these changes
LGTM

2021-07-29 07:56 UTC, merged