Feature/vagrant
stackabletech/test-dev-cluster pull request #38
Opened 2021-09-01 16:01 UTC by razvan

# Description

Use Vagrant and VirtualBox to spin up dev/test environments. See `vagrant/README.md` for details.

Fixes #39

## What works

* Testing all operators on debian10, 11, centos7, 8
* Testing the agent.

## What doesn't work yet

* many things probably ...

## TODO

- [x] Make the agent testable
- **Dropped**: Figure out how to package and publish boxes
- **Dropped**: Solve the secure boot problem

2021-09-06 12:39 UTC, berndfo commented
I tried the process and it in general works. lgtm.
Findings:
* Had to manually create the `./rancher` folder, should be pre-created or tolerate the absence.
* Rename the folder from "rancher" to "cluster-mounted-data" or similar

2021-09-06 20:48 UTC, berndfo approved these changes
lgtm

2021-09-13 11:18 UTC, siegfriedweber requested changes
After adding the `server-bind-ip` argument, the agent integration tests were executed successfully.

2021-09-13 11:18 UTC, siegfriedweber commented on vagrant/README.md
> +    cargo run --target-dir /build/agent --bin stackable-agent -- --hostname=localhost
If the hostname is set to `localhost` then the server must be bound to `127.0.0.1`. Otherwise the log tests will fail.

```suggestion
    cargo run --target-dir /build/agent --bin stackable-agent -- --hostname=localhost --server-bind-ip=127.0.0.1
```

2021-09-14 07:26 UTC, razvan commented on vagrant/README.md
> +    cargo run --target-dir /build/agent --bin stackable-agent -- --hostname=localhost
Done. Thanks.

2021-09-14 10:20 UTC, siegfriedweber approved these changes
agent-integration-tests successfully tested

2021-09-14 11:29 UTC, merged